version: '3.8'
services:
  api:
    image: api
    links:
      - "auth:auth"
    build: 
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - auth
    networks:
      - app

  db:
    image: postgres:13.3
    restart: always
    ports:
      - 55432:5432
    env_file: api/.env
    volumes:
      - .dbdata:/var/lib/postgresql
    networks:
      - app

  auth:
    image: auth
    command: node src/server.js
    build:
      context: ./auth-service
    ports:
      - 8081:8081
    env_file: auth-service/.env
    volumes:
      - .:/app/
    networks:
      - app

networks:
  app:
